### ISSUE TITLE
运行不了啊

### ISSUE THREAD

**Issue by wubangjunjava** [SuperLinkStudio/SMSboom-HXCZ#2]
运行不了啊

Traceback (most recent call last):
  File "E:\ai\SMSBoom-HXCZ-v1.2.4\smsboom.py", line 69, in load_json
18:40:15,928 [    datas = json.loads(j.read())
  File "D:\work\Python\Python310\lib\json\__init__.py", line 346, in loads
ERROR    return _default_decoder.decode(s)
]   File "D:\work\Python\Python310\lib\json\decoder.py", line 337, in decode
MainThread    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "D:\work\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
smsboom    raise JSONDecodeError("Expecting value", s, err.value) from None
:json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
77
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 -   File "E:\ai\SMSBoom-HXCZ-v1.2.4\smsboom.py", line 216, in <module>
Json file syntax error:Expecting value: line 1 column 1 (char 0)    cli()

  File "D:\work\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\work\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\work\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\work\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\work\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\ai\SMSBoom-HXCZ-v1.2.4\smsboom.py", line 166, in oneRun
    _api = load_json()
  File "E:\ai\SMSBoom-HXCZ-v1.2.4\smsboom.py", line 78, in load_json
    raise ValueError
ValueError

**Comment by 1a20932** [comment]
Emmm...
本人目前小学生5年级，大致判断云服务问题，马上修复

**Comment by 1a20932** [comment]
微信：liuqinyu-code

**Comment by 1a20932** [comment]
QQ:2295326064

**Comment by 1a20932** [comment]
麻烦把您的文件全部发给我，或者做一个虚拟环境?
